// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: butler.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomPort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port   int32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Exists bool  `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *RoomPort) Reset() {
	*x = RoomPort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPort) ProtoMessage() {}

func (x *RoomPort) ProtoReflect() protoreflect.Message {
	mi := &file_butler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPort.ProtoReflect.Descriptor instead.
func (*RoomPort) Descriptor() ([]byte, []int) {
	return file_butler_proto_rawDescGZIP(), []int{0}
}

func (x *RoomPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RoomPort) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type RoomName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RoomName) Reset() {
	*x = RoomName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomName) ProtoMessage() {}

func (x *RoomName) ProtoReflect() protoreflect.Message {
	mi := &file_butler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomName.ProtoReflect.Descriptor instead.
func (*RoomName) Descriptor() ([]byte, []int) {
	return file_butler_proto_rawDescGZIP(), []int{1}
}

func (x *RoomName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_butler_proto protoreflect.FileDescriptor

var file_butler_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x75, 0x74, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x63, 0x68, 0x61, 0x74, 0x22, 0x36, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6f, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x1e, 0x0a, 0x08,
	0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x66, 0x0a, 0x06,
	0x42, 0x75, 0x74, 0x6c, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x0e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x50, 0x6f, 0x72, 0x74, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x0e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x1a, 0x0e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6f,
	0x72, 0x74, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_butler_proto_rawDescOnce sync.Once
	file_butler_proto_rawDescData = file_butler_proto_rawDesc
)

func file_butler_proto_rawDescGZIP() []byte {
	file_butler_proto_rawDescOnce.Do(func() {
		file_butler_proto_rawDescData = protoimpl.X.CompressGZIP(file_butler_proto_rawDescData)
	})
	return file_butler_proto_rawDescData
}

var file_butler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_butler_proto_goTypes = []interface{}{
	(*RoomPort)(nil), // 0: chat.RoomPort
	(*RoomName)(nil), // 1: chat.RoomName
}
var file_butler_proto_depIdxs = []int32{
	1, // 0: chat.Butler.CreateRoom:input_type -> chat.RoomName
	1, // 1: chat.Butler.FindRoom:input_type -> chat.RoomName
	0, // 2: chat.Butler.CreateRoom:output_type -> chat.RoomPort
	0, // 3: chat.Butler.FindRoom:output_type -> chat.RoomPort
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_butler_proto_init() }
func file_butler_proto_init() {
	if File_butler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_butler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_butler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_butler_proto_goTypes,
		DependencyIndexes: file_butler_proto_depIdxs,
		MessageInfos:      file_butler_proto_msgTypes,
	}.Build()
	File_butler_proto = out.File
	file_butler_proto_rawDesc = nil
	file_butler_proto_goTypes = nil
	file_butler_proto_depIdxs = nil
}
